// I DO NOT OWN THE FOLLOWING CODE - IT IS BASED OFF OF CODE PROVIDED TO THE CLASS VIA A DRIVER FILE TO TEST FUNCTIONALITY
#pragma once
void table_test0(void);
void table_test1(void);
void table_test2(void);
void table_test3(void);
void table_test4(void);
void table_test5(void);
void table_test6(void);
void table_test7(void);
void table_test8(void);
void table_test9(void);
void table_test10(void);
void table_test11(void);
void table_test12(void);
void table_test13(void);
void table_test14(void);
void table_test15(void);
void table_test16(void);
void table_test17(void);
void table_test18(void);
void table_test19(void);
void table_test20(void);
void table_test21(void);