// I DO NOT OWN THE FOLLOWING CODE - IT IS BASED OFF OF CODE PROVIDED TO THE CLASS VIA A DRIVER FILE TO TEST FUNCTIONALITY
#pragma once
void List_TestPushFront(void);
void List_TestPushBack(void);
void List_TestPushFrontBack(void);
void List_TestPopFront(void);
void List_TestArray1(void);
void List_TestArray2(void);
void List_TestCopyConstructor1(void);
void List_TestCopyConstructor2(void);
void List_TestAssignment1(void);
void List_TestAssignment2(void);
void List_TestAddition1(void);
void List_TestAddition2(void);
void List_TestAddAssign1(void);
void List_TestAddAssign2(void);
void List_TestAddAssign3(void);
void List_TestAddAssign4(void);
void List_TestSubscript1(void);
void List_TestSubscript2(void);